Repository GMOD/Chado, pull requests merged in 2019-03, with the labels that each got.

#99 Matrix
  .travis.yml
  chado/migrations/V1.3.3.001__add_stock_biomat_table.sql
Labels: small change

#97 PR Guidelines (1st stage of governance)
  docs/contributing.rst
  docs/contributing/PR_guidelines.rst
  docs/index.rst
Labels: large change

#95 94 flyway guide
  docs/index.rst
  docs/using_flyway.rst
Labels: small change

#101 Build schemaspy documentation continuously and host on RTD
  .travis.yml
  docs/index.rst
  docs/schema_definition.rst
Labels: documentation, small change

#103 fix typo in link to schemaspy
  docs/schema_definition.rst
Labels: small change
